name: muvam_rider
description: A Flutter rider application
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & UX
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  fl_chart: ^1.1.1
  another_flushbar: ^1.12.32
  pinput: ^5.0.0

  # Maps & Location
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Networking & Connectivity
  http: ^1.1.0
  connectivity_plus: ^6.1.2
  web_socket_channel: ^2.4.0

  # Firebase & Notifications
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.5.2
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0

  # State & Storage
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Device & Platform
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  local_auth: ^2.3.0
  vibration: ^3.1.5
  wakelock_plus: ^1.4.0
  audioplayers: ^5.2.1
  flutter_ringtone_player: ^4.0.0+4

  # Utilities
  intl: ^0.20.2
  logger: ^2.6.2
  url_launcher: ^6.2.4
  share_plus: ^12.0.1
  country_picker: ^2.0.26
  flutter_dotenv: ^6.0.0
  agora_rtc_engine: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/sounds/
    - assets/firebase-service-account.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
